{
 "title": "search_engine_crawler",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Crawler page parse time",
   "type": "graph",
   "description": "Время затраченное ботом на обработку содержимого веб-страницы",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "crawler_page_parse_time_bucket" }
   ]
  },
  {
   "title": "Parsed pages",
   "type": "singlestat",
   "description": "Количество обработанных ботом страниц",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "crawler_pages_parsed" }
   ]
  },
  {
   "title": "Сrawler site connection time",
   "type": "graph",
   "description": "Время затраченное ботом на подключение к веб-сайту и загрузку веб-страницы",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_site_connection_time_bucket"
    }
   ]
  }
 ]
}